### ISSUE TITLE
.inherit macro

### ISSUE THREAD

**Issue by allanjude** [vstakhov/libucl#100]
For specifying defaults

defaults {
  key = "val"
  foo = "bar"
  many = "values here"
}

mything {
  .inherit "defaults"
  key = "newval"
}

results in:
mything {
  foo = "bar"
  many = "values here"
  key = "newval"
}

**Comment by allanjude** [comment]
This was just a todo item for myself, thanks for jumping on it so quick. I plan to use this as part of converting login.conf to UCL in FreeBSD.

**Comment by Crest** [comment]
The `.inherit` macro only works for top level configuration objects. It can't index into objects e.g. `.inherit defaults.resource_limits` this requires users of `.inherit` to pollute the top level configuration object and effectively prevents validating the configuration against a meaningful schema.
