### ISSUE TITLE
File name collision

### ISSUE THREAD

**Issue by cicku** [vstakhov/libucl#101]
Hi, 

This lib uses libucl as name of library files. However it has been used by many distros for UCL Compression Library from lzo upstream. Any idea on how to solve the name issue? 

http://www.oberhumer.com/opensource/ucl/

**Comment by vstakhov** [comment]
That's a problem of packages managers. I see no point in changing the name in honor of a library that hasn't been updated for 10 years so far. It's just irrational.

**Comment by cicku** [comment]
I just hope this library will not be used by rspamd, or no distro will package it since UCL has been there for decades.
