### ISSUE TITLE
lua binding for json schema validation

### ISSUE THREAD

**Issue by bjne** [vstakhov/libucl#104]
I would very much like to have access to the json schema validation
api via lua/luajit. Is this going to happen any time soon, and is it possible to sponsor it?

**Comment by vstakhov** [comment]
I've added the initial version of this support invoked as 

```lua
local res, err = parser:validate(schema)

if res then ... else ... end
```

Schema can be either lua table that represents json schema (it might be even previously loaded) or filename that `libucl` would load, parse and validate the original parser's object against it.

**Comment by bjne** [comment]
Hello, sounds great, but I am unable to build the lua lib:

make[2]: Entering directory `/home/bjornar/broadnet/api/lua-libs/libucl/lua'
  CC       ucl_la-lua_ucl.lo
  CCLD     ucl.la
/usr/bin/ld: //usr/local/lib/liblua.a(lapi.o): relocation R_X86_64_32 against `luaO_nilobject_' can not be used when making a shared object; recompile with -fPIC
//usr/local/lib/liblua.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status

**Comment by vstakhov** [comment]
It seems you are trying to ling statically compiled lua library to a shared object. Moreover, it seems your lua library is compiled without -fPIC option. That's definitely not a ucl issue. I'm pretty sure you can still compile libucl statically by specifying `--disable-shared` when running `./configure`.

**Comment by bjne** [comment]
I have had no problems building shared libraries against this earlier.. Guess I need to look
closer at whats going on. Thanks.

**Comment by bjne** [comment]
Solution:
 LUA_LIB=-lluajit-5.1 LUA_INCLUDE=-I/usr/local/include/luajit-2.0 LUA=/usr/local/bin/luajit ./configure --enable-lua --enable-shared
