### ISSUE TITLE
Comment code results in doubles

### ISSUE THREAD

**Issue by allanjude** [vstakhov/libucl#116]
Output with comments retained results in any consecutive comments being duplicated

double_comment.in:
```
key1 = 1;
#comment1
#comment2
key2 = 2;
```

result:
test_basic -C double_comment.in
```
#comment1
#comment2
key1 = 1;
#comment1
#comment2
key2 = 2;
```

It does not happen if the comments are not consecutive:
normal.in:
```
key1 = 1;
#comment1
key2 = 2;
#comment2
key3 = 3;
```

test_basic -C normal.in
```
key1 = 1;
#comment1
key2 = 2;
#comment2
key3 = 3;
```

**Comment by vstakhov** [comment]
I can't reproduce it:

```
% tests/test_basic -C
key1 = 1;
#comment1
#comment2
key2 = 2;
^D
key1 = 1;
#comment1
#comment2
key2 = 2;
```

**Comment by allanjude** [comment]
It looks like you last commit, "Allow comments placement before and after object" fixed this

**Comment by allanjude** [comment]
I am still seeing this:

% tests/test_basic -C
```
foo = "bar"; #explanation
# whole line comment
line = "comment";
# second line comment
second = "line";
after = "line"; /* after comment */
/* prefix comment */ silly = "prefix";


```
^D
```
#explanation
# whole line comment
foo = "bar";
#explanation
# whole line comment
line = "comment";
# second line comment
second = "line";
after = "line";
/* after comment */
/* prefix comment */
silly = "prefix";
```



Actually, if I run it with the same input repeatedly, I get different output.

One time I got:
```
foo = "bar";
#explaination
# whole line comment
/* after comment */
line = "comment";
# second line comment
second = "line";
#explaination
# whole line comment
after = "line";
#explaination
# whole line comment
/* after comment */
silly = "prefix";
```

**Comment by allanjude** [comment]
The issue seems to be with using (const char *)&obj as the key for the comments object

It seems when that the pointer happens to end in 00, it is interpreted as a null byte, and then the comment key matches multiple object keys, and the same comment gets attached multiple times.

Or something like that. It makes it hard to track down, as it doesn't happen every time

**Comment by vstakhov** [comment]
You are right. I've replaced bad strncmp calls with plain memcmp and it works now. Thanks you!

**Comment by allanjude** [comment]
confirmed fixed
