### ISSUE TITLE
Macro help

### ISSUE THREAD

**Issue by dangerousHobo** [vstakhov/libucl#131]
Could someone please explain how to use .macro? I'm trying to figure out how to define and use my own macro but I'm not having any luck. Some more complete examples than what the README provides would be helpful. I'm so confused on how to use it.

Thank you.

**Comment by raviqqe** [comment]
I'm also confused about how to use macros. Macro directives in other languages I know are used with a name, parameters, and a body.

For example,
```ucl
macro my_macro_name($param1, $param2) {
    foo {
        bar = [$param1, 123];
        baz = [true, $param2];
    }
}; 
```

However, examples of ucl in README don't seem to have any macro name.

**Comment by denisvm** [comment]
The README states only how to use a builtin/registered macro. You can register a new macro with the function [`ucl_parser_register_macro`](https://github.com/vstakhov/libucl/blob/master/doc/api.md#ucl_parser_register_macro). The `.include` feature is a builtin macro for instance.

**Comment by raviqqe** [comment]
It's clear to me now. Then, it seems to be confusing to use `macro` as a macro name in examples. We'd better to use something more explicit like `some_macro` or `my_macro`. What do you think?

**Comment by denisvm** [comment]
@raviqqe It might be a good idea, perhaps we could use `.macro_name` and/or reference it in the README file.
