### ISSUE TITLE
Including an empty file causes a segmentation fault

### ISSUE THREAD

**Issue by chmeeedalf** [vstakhov/libucl#153]
Including an empty file from another file causes a segmentation fault in ucl_state_machine, near the end of the 'case UCL_STATE_MACRO' section.  "parser->chunks" becomes NULL, so it ends up dereferencing a NULL pointer when getting chunk->pos.

**Comment by vstakhov** [comment]
I cannot reproduce it. Including of empty file just causes nothing.

**Comment by chmeeedalf** [comment]
Looks like this was closed back in April with 0c24799829f2252440ac5975d59599e78b6e4a0b
