### ISSUE TITLE
parsing option UCL_PARSER_NO_IMPLICIT_ARRAYS

### ISSUE THREAD

**Issue by richardbowden** [vstakhov/libucl#178]
HI,

I am struggling to understand why / when to use UCL_PARSER_NO_IMPLICIT_ARRAYS vs not using it? Any guidance would be great ?

**Comment by allanjude** [comment]
In the default case:
key1 = val1
key1 = val2

You will get a single object, with 2 values, you need to use the interator function to get the 2nd value.

with NO_IMPLICIT_ARRAYS you will get an explicit array object, containing the 2 items as children.
