### ISSUE TITLE
ucl_object_delete_key has bug and cause segmentation fault when emitting ucl_object

### ISSUE THREAD

**Issue by mars90226** [vstakhov/libucl#179]
The internal ucl_hash in ucl_object_t use khash for getting object using key and kvec for quickly iterating objects. And the khash entry has a field called ar_idx to identify the object location in kvec.
In ucl_hash_delete, it will try to get the hash entry from khash to be deleted and delete the item at ar_idx in kvec. But it will not update other hash entry that has ar_idx larger than the one to be deleted. Thus, when calling ucl_hash_delete to delete second key and again to delete third key. It will make khash and kvec not in sync.

I've run into this problem when I delete the second key and the third key from a 3-elements hash (object). After that, emitting the hash will result in segmentation fault.

**Comment by vstakhov** [comment]
I have already fixed it in Rspamd and will backport this fix back to libucl. Thank you very much for your report!

**Comment by vstakhov** [comment]
This is now merged.

**Comment by mars90226** [comment]
Thank you.
