### ISSUE TITLE
Variable handler doesn't seep to be working

### ISSUE THREAD

**Issue by andoriyu** [vstakhov/libucl#217]
There two call sites for handler, [first](https://github.com/vstakhov/libucl/blob/master/src/ucl_parser.c#L344-L354) to check if variable is a variable and [second](https://github.com/vstakhov/libucl/blob/master/src/ucl_parser.c#L462-L471) one is expansion.

On first call everything is right. However, on second call, pointer to variable name is 2 bytes off: instead of say `WWW` from `${WWW}` i get pointer to `${W`

If I change `ptr` to `ptr + 2` [here](https://github.com/vstakhov/libucl/blob/master/src/ucl_parser.c#L464) everything works.

Minimal example: https://gist.github.com/andoriyu/7d8e148e706a1d8fefbacadb656a7e44

Please help.

**Comment by andoriyu** [comment]
When it's merged, is it possible to cut a new release?

**Comment by vstakhov** [comment]
I'm currently trying to get some oss-fuzz results and fix issues there as well. But thanks for a good catch, I'll merge it asap.
