### ISSUE TITLE
ucl_lookup_path() Dot Notation

### ISSUE THREAD

**Issue by bdrewery** [vstakhov/libucl#24]
It would be nice to have `ucl_lookup_path("parent.child.key")` and `ucl_lookup_path("parent.child[index]")` to walk the tree and return the object if found.
##

**Comment by ThomasAdam** [comment]
Hi,

I appreciate this is a very old issue, but I was just comparing `libconfig` with `libucl`, and I really do think that `libucl` could benefit from a dot-notation lookup string, as @bdrewery has demonstrated.

I'd be happy to pick up the work that Bryan started, assuming it would be a welcomed addition to `libucl`?  Was there ever a reason why this didn't get taken any further?

**Comment by vstakhov** [comment]
No problems, this issue should be indeed closed.
