### ISSUE TITLE
streamline API generates invalid json

### ISSUE THREAD

**Issue by bapt** [vstakhov/libucl#277]
when exporting to json_compact using streamline API

If I create an array, which I populate with objects, ,then close the arrary of contianer there is a missing "," before the key of the next object
```
{ "packages": [ {OBJ1}, {OBJ2}, {OBJ3}]"groups": [...] }
```

**Comment by vstakhov** [comment]
Thank you for the report! Do you have a piece of code to reproduce this issue by chance?

**Comment by bapt** [comment]
convert test/test_streamline.c to expose COMPACT_JSON and you have a broken example
