### ISSUE TITLE
The backport of fixes from rspamd also restored a bug that was fixed in libucl, but not in rspamd.

### ISSUE THREAD

**Issue by Crest** [vstakhov/libucl#287]
This commit c4fc60ebb0aa695df1e6642770d512adb9f1af4e restores the regression already fixed once before in PR #240. The `*out_len = dstlen;` (line 351 of `ucl_parser.c` at the time) was required because otherwise if the `var_handler` callback returns `true` the parser will replace the variable with the zero-length aka empty string.

**Comment by vstakhov** [comment]
I have fixed in in Rspamd, so I think I need to fix it one more time here :( Thanks for a good finding!
