### ISSUE TITLE
Unfortunate name clash with UCL (data compression library)

### ISSUE THREAD

**Issue by dmacvicar** [vstakhov/libucl#29]
While packaging libucl for a distribution, I noticed there was already a libucl packaged:

http://www.oberhumer.com/opensource/ucl/

**Comment by jbergstroem** [comment]
Just pinging here again; we just ran into this issue in gentoo. Would you perhaps consider being able to rename/prefix libucl as part of the build system?

https://bugs.gentoo.org/show_bug.cgi?id=573986

**Comment by vstakhov** [comment]
Well, I won't repeat my error I've done with rspamd. There will be *NO* system specific things in libucl. If you want to rename .sofile or to add conflitc - it's up to you and your package system. Any package system allows placing local patches for external software. So I'd suggest to go this way.

**Comment by dmacvicar** [comment]
I don't think renaming the whole library because of its name should be distribution work. It will create all kind of meta-problems: eg: name of the pkg-config file which is used to figure all the rest?

The incentive to get your software distributed should be on your side. I opt for not packaging it, so feel free to close the issue.
