### ISSUE TITLE
ucl_object_delete_key deletes everything after the deleted object

### ISSUE THREAD

**Issue by allanjude** [vstakhov/libucl#71]
if you call ucl_object_delete_key(parent, keyname);

every object after that key disappears. The 'len' on the parent is correct, but the other objects disappear.

example:
with the ucl object: { one: 1, two: 2, three: 3, four: 4, five: 5 }

$ ./del_repro
one = 1
two = 2
three = 3
four = 4
five = 5

but if you delete "three"
$ ./del_repro three
one = 1
two = 2

then "four" and "five" disappear

Reproduction code:

#include <stdio.h>
#include <errno.h>

#include "ucl.h"

int
main(int argc, char *argv[])
{
    ucl_object_t *root_obj = NULL;
    struct ucl_parser *parser = NULL;
    ucl_object_iter_t it;
    const ucl_object_t *cur;
    bool perr = false, success = false;

    /* Initialize parser */
    parser = ucl_parser_new(UCL_PARSER_KEY_LOWERCASE);

    perr = ucl_parser_add_string(parser, "{ one: 1, two: 2, three: 3, four: 4, five: 5 }", 0);
    if (perr == false) {
	exit(1);
    } else {
	root_obj = ucl_parser_get_object(parser);
    }

    if (ucl_parser_get_error(parser)) {
	fprintf(stderr, "Error: Parse Error occured: %s\n",
	    ucl_parser_get_error(parser));
	exit(2);
    }

    if (argc > 1) {
	success = ucl_object_delete_key(root_obj, argv[1]);
	if (success == false) {
	    fprintf(stderr, "failed to delete key\n");
	    exit(3);
	}
    }

    it = ucl_object_iterate_new (root_obj);
    while ((cur = ucl_object_iterate_safe (it, true)) != NULL) {
	printf("%s = %ld\n", ucl_object_key(cur), ucl_object_toint(cur));
    }
    ucl_object_iterate_free (it);

    if (parser != NULL) {
	ucl_parser_free(parser);
    }
    if (root_obj != NULL) {
	ucl_object_unref(root_obj);
    }

    return(0);
}

**Comment by vstakhov** [comment]
I have fixed it in the master branch. Thank you for an excellent report!
