### ISSUE TITLE
sigbus caused by new include code

### ISSUE THREAD

**Issue by allanjude** [vstakhov/libucl#75]
If there are any implicit arrays in files when you use includes, libucl crashes:

if you have this input file:

16.in:
.include(priority = 1) "${CURDIR}/16.inc"

section = {
        value = "test";
}

overrided = {
        value = "not-to-be-shown";
}
overrided = {
        value2 = "implicit-array";
}

if you ignore the include statement, the output is rendered as:
section {
    value = "test";
}
overrided [
    {
        value = "not-to-be-shown";
    }
    {
        value2 = "implicit-array";
    }
]

But with the include:
16.inc:
overrided {
        key = "overrided";
}

the output is:
overrided {
    key = "overrided";
}
section {
    value = "test";
}

Program received signal SIGBUS, Bus error.
0x0000000800838f20 in ucl_parser_free (parser=0x801806080) at ucl_util.c:461
461             LL_FOREACH_SAFE (parser->trash_objs, tr, trtmp) {

**Comment by allanjude** [comment]
this might be related to this regression: https://github.com/vstakhov/libucl/commit/29910c7fdda02e6868424c7ad4a573f628f4a0ea#commitcomment-11121318

Your recent commit undid a change I made in pull request #66

**Comment by vstakhov** [comment]
Seems to be fixed now, thank you!
