### ISSUE TITLE
ucl_object_set_priority does not work as intended

### ISSUE THREAD

**Issue by allanjude** [vstakhov/libucl#79]
Because ucl_object_set_priority does an OR operation on obj->flags, setting the priority on an object that already has a priority does not work as intended.

printf("root_obj.priority = %d\n", ucl_object_get_priority(root_obj));
ucl_object_set_priority(root_obj, 4);
printf("root_obj.priority = %d\n", ucl_object_get_priority(root_obj));
ucl_object_set_priority(root_obj, 2);
printf("root_obj.priority = %d\n", ucl_object_get_priority(root_obj));

produces:
root_obj.priority = 0
root_obj.priority = 4
root_obj.priority = 6

**Comment by vstakhov** [comment]
Should work now.

**Comment by vstakhov** [comment]
BTW, if you can convert your tests to some isolated unit tests that would be cool in future to avoid occasionally regressions.

**Comment by allanjude** [comment]
Works as intended now
