### ISSUE TITLE
Get raw error code

### ISSUE THREAD

**Issue by hauleth** [vstakhov/libucl#82]
Currently there is only `ucl_parser_get_error` that returns `const char*` but in my [Rust wrapper](https://github.com/hauleth/ucl-rs) I want to use "raw" error codes (as there is `enum ucl_error` that is used nowhere) to allow user to "manually" provide suitable error message.

**Comment by vstakhov** [comment]
This is done now.

**Comment by hauleth** [comment]
❤️

--
Łukasz Jan Niemier

Dnia 29 maj 2015 o godz. 14:58 Vsevolod Stakhov <notifications@github.com> napisał(a):
