### ISSUE TITLE
feature: include a file as a multi-line string

### ISSUE THREAD

**Issue by allanjude** [vstakhov/libucl#84]
A new macro, named .contents or .file or something

the args would include file=/path/to/file
and the 'data' would be the key name
so:

.contents(file=/etc/motd) "motd";

would result in:
motd = <<<EOD
my motd
goes
here
EOD;

Looking for some feedback before I wrote the code for this.

**Comment by vstakhov** [comment]
I'd suggest to reverse order of macro and rename it to something like `.load_file` or just `.load`:

    .load(multiline=true,key="key") "/etc/motd"
    .load(format="csv",target="array") "/blah.csv"

And so on. In this version we'd have more flexibility.

**Comment by allanjude** [comment]
I like that. This is why I asked first.

**Comment by allanjude** [comment]
That was merged already
