### ISSUE TITLE
Macro parser error if arguments contain double quotes

### ISSUE THREAD

**Issue by allanjude** [vstakhov/libucl#87]
Macros such as this example from the README:
.macro(key="()") "something";
result in a parse error

    /* Initialize parser */
    parser = ucl_parser_new(UCL_PARSER_KEY_LOWERCASE);

    perr = ucl_parser_add_string(parser, ".include(try=true, something=\"broken\") \"somefile\";", 0);
    if (perr == false) {
        if (ucl_parser_get_error(parser)) {
                fprintf(stderr, "Error: Parse Error occured: %s\n", ucl_parser_get_error(parser));
        }
    }

Error: Parse Error occured: error while parsing <unknown>: line: 1, column: 38 - 'macro arguments parsing error', character: '0x20'

**Comment by vstakhov** [comment]
It seems it's space character that caused this issue. I'll check...

**Comment by allanjude** [comment]
It says it is the same, but if you remove the quotes in the argument for the macro, the error goes away.

**Comment by allanjude** [comment]
This appears to be fixed
